# SPDX-License-Identifier: GPL-2.0-only

intel-ipu6-psys-objs			+= ipu6-psys.o \
					   ipu6-psys-cmd.o \
					   ipu6-psys-fw.o \
					   ipu6-psys-gem.o

obj-$(CONFIG_DRM_ACCEL_INTEL_IPU6_PSYS)	+= intel-ipu6-psys.o
